name: Datadog Pipeline

on:
  workflow_dispatch:
  

jobs:

 Install-Datadog-Agent:
   runs-on: ubuntu-latest
   steps:
     - name: Start the Datadog Agent locally
       run: ls
       
#      - name: Download Build Artifact
#        if: ${{ always() }}
#        uses: actions/download-artifact@v1
#        with:
#           name: unit-test-results
     - uses: actions/setup-python@v3
       with:
          python-version: '3.x' 
          architecture: 'x64'
#      - run: python my_script.py  
     - name: setting up pip
       run: | 
          sudo apt update
          sudo apt install python3-pip
          
          
     - name: checking 
       run: ls
       
     - name: install pandoc 
       run: sudo apt install pandoc
       
#      - name: install tidy
#        run: sudo apt install tidy
       
#      - name: check tidy
#        run: tidy --version
     - name: convert md to html
       run: pandoc ./testfile/lint.md -f markdown -t html -s -o input.html
       
     - name:  running html to xml
       run: python .github/scripts/converthtmltoxml.py
       
