name: Setup JFrog CI

on:
  workflow_dispatch:

jobs:
  Linting:

    runs-on: ubuntu-latest

       

    steps:
    - uses: actions/checkout@v3
    
    - name: Install CLI
      run: |
        wget -qO - https://releases.jfrog.io/artifactory/jfrog-gpg-public/jfrog_public_gpg.key | sudo apt-key add -
        echo "deb https://releases.jfrog.io/artifactory/jfrog-debs xenial contrib" | sudo tee -a /etc/apt/sources.list;
        apt update;
        apt install -y jfrog-cli-v2-jf;
        
        
    - name: checking jfrog cli version
      run: jf --version
