name: Node.js CI

on:
  workflow_dispatch:

jobs:
  Linting:

    runs-on: ubuntu-latest

       

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - name: installing angular cli
      run: npm i -g @angular/cli
    - name: instaling eslint package
      run: ng add @angular-eslint/schematics
    - name: running linting
      run: ng lint > lintlogs.txt
    - name: checking wether lint files
      run: cat lintlogs.txt
