name: Node.js CI

on:
  workflow_dispatch:

jobs:
  Linting:

    runs-on: ubuntu-latest

       

    steps:
    - uses: actions/checkout@v3
    
    - name: branch nalmel
      run: |
        echo "branch is ${github.ref}"
        
        
    - run: echo "brancjh id ${GITHUB_REF}"
    - run: git rev-parse --abbrev-ref HEAD
