name: Node.js CI

on:
  workflow_dispatch:

jobs:
  Linting:

    runs-on: ubuntu-latest

       

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - name: installing angular cli
      run: npm i -g @angular/cli
    - name: instaling eslint package
      run: ng add @angular-eslint/schematics
    - name: Super-Linter
      uses: github/super-linter@v4.9.2
      env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JSON: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JAVASCRIPT_STANDARD: true
   
