name: Node.js CI

on:
  workflow_dispatch:

jobs:
  Linting:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
       

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: installing angular cli
      run: npm i -g @angular/cli
    - name: instaling eslint package
      run: ng add @angular-eslint/schematics
      
    - name: converting ts lint packages to es lint
      run: ng g @angular-eslint/schematics:convert-tslint-to-eslint --remove-tslint-if-no-more-tslint-targets --ignore-existing-tslint-config
    - name: running linting
      run: ng lint > lintlogs.txt
    - name: checking wether lint files
      run: cat lintlogs.txt
